// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Novati.API.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Novati.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261007123430_SessaoRemotaAgente")]
    partial class SessaoRemotaAgente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Novati.API.Models.Entities.Artigo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("Artigos");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.ArtigoAvaliacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtigoId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Util")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ArtigoId", "UserId")
                        .IsUnique();

                    b.ToTable("ArtigoAvaliacoes");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.Compatibilidade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModeloComponenteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModeloDispositivoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ModeloDispositivoId");

                    b.HasIndex("ModeloComponenteId", "ModeloDispositivoId")
                        .IsUnique();

                    b.ToTable("Compatibilidades");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.DispositivoFisico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DataAquisicao")
                        .HasColumnType("date");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("GarantiaMeses")
                        .HasColumnType("integer");

                    b.Property<Guid>("LocalizacaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModeloDispositivoId")
                        .HasColumnType("uuid");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Patrimonio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ResponsavelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocalizacaoId");

                    b.HasIndex("ModeloDispositivoId");

                    b.HasIndex("Patrimonio")
                        .IsUnique();

                    b.HasIndex("ResponsavelId");

                    b.ToTable("DispositivosFisicos");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.Ficheiro", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CaminhoRelativo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CriadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorId");

                    b.ToTable("Ficheiros");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.InstanciaComponente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("DispositivoFisicoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ModeloComponenteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DispositivoFisicoId");

                    b.HasIndex("ModeloComponenteId");

                    b.ToTable("InstanciasComponentes");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.ItemStock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModeloComponenteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ModeloComponenteId")
                        .IsUnique();

                    b.ToTable("ItensStock");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.Localizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("PaiId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PaiId");

                    b.ToTable("Localizacoes");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.Mensagem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("Lida")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SolicitacaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("SolicitacaoId");

                    b.ToTable("Mensagens");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.ModeloComponente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Capacidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("StockMinimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ModelosComponente");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.ModeloDispositivo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ModelosDispositivo");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.MovimentoStock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<Guid>("ItemStockId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ItemStockId");

                    b.ToTable("MovimentosStock");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.Notificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<bool>("Lida")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.OrdemHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AutorId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<Guid>("OrdemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Posicao")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("OrdemId");

                    b.ToTable("OrdemHistoricos");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.OrdemPecaUsada", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InstaladoInstanciaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModeloComponenteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrdemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UnidadeStockId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InstaladoInstanciaId");

                    b.HasIndex("ModeloComponenteId");

                    b.HasIndex("OrdemId");

                    b.HasIndex("UnidadeStockId");

                    b.ToTable("OrdemPecasUsadas");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.OrdemRejeicao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("OrdemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrdemId");

                    b.ToTable("OrdemRejeicoes");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.OrdemReparo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConcluidaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("EsperaValidacaoSeg")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("IniciadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PropostaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SolicitacaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Solucao")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("SolucaoSugerida")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("TecnicoId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TempoGastoMin")
                        .HasColumnType("integer");

                    b.Property<int?>("TempoTrabalhoMin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SolicitacaoId")
                        .IsUnique();

                    b.HasIndex("TecnicoId");

                    b.ToTable("OrdensReparo");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.RelatorioHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Campo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<int>("Posicao")
                        .HasColumnType("integer");

                    b.Property<Guid>("RelatorioId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValorAntigo")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ValorNovo")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("RelatorioId");

                    b.ToTable("RelatorioHistoricos");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.RelatorioTecnico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AssinaturaResponsavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssinaturaTecnico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("AssinaturaTecnicoFicheiroId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AtualizadoEm")
                        .HasColumnType("date");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ComentariosInternos")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateOnly>("CriadoEm")
                        .HasColumnType("date");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("OrdemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Procedimentos")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("SolucaoAplicada")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sumario")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("TempoGastoMin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssinaturaTecnicoFicheiroId");

                    b.HasIndex("AutorId");

                    b.HasIndex("OrdemId")
                        .IsUnique();

                    b.ToTable("RelatoriosTecnicos");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.RequisicaoCompra", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ItemStockId")
                        .HasColumnType("uuid");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ModeloComponenteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrdemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<Guid>("SolicitanteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemStockId");

                    b.HasIndex("ModeloComponenteId");

                    b.HasIndex("OrdemId");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("RequisicoesCompra");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.SessaoRemota", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AgentePc")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AutorizadaIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("IniciadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Modo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MotivoFim")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("PedidaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RespondidaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SolicitacaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SolicitanteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TecnicoId")
                        .HasColumnType("uuid");

                    b.Property<int>("TentativasFalhadas")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TerminadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TerminadaPorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("TokenExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("TokenUsadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("SolicitacaoId")
                        .IsUnique()
                        .HasFilter("\"Estado\" IN ('PEDIDA', 'AUTORIZADA', 'ATIVA')");

                    b.HasIndex("SolicitanteId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("SessoesRemotas");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.Solicitacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("DataCriacao")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid?>("DispositivoFisicoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ResolvidaViaBase")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SolicitanteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("DispositivoFisicoId");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("Solicitacoes");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.UnidadeStock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ItemStockId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReservadaParaOrdemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ItemStockId");

                    b.HasIndex("ReservadaParaOrdemId");

                    b.ToTable("UnidadesStock");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssinaturaFicheiroId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssinaturaFicheiroId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.Artigo", b =>
                {
                    b.HasOne("Novati.API.Models.Entities.User", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.ArtigoAvaliacao", b =>
                {
                    b.HasOne("Novati.API.Models.Entities.Artigo", "Artigo")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("ArtigoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Novati.API.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artigo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.Compatibilidade", b =>
                {
                    b.HasOne("Novati.API.Models.Entities.ModeloComponente", "ModeloComponente")
                        .WithMany()
                        .HasForeignKey("ModeloComponenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Novati.API.Models.Entities.ModeloDispositivo", "ModeloDispositivo")
                        .WithMany()
                        .HasForeignKey("ModeloDispositivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModeloComponente");

                    b.Navigation("ModeloDispositivo");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.DispositivoFisico", b =>
                {
                    b.HasOne("Novati.API.Models.Entities.Localizacao", "Localizacao")
                        .WithMany()
                        .HasForeignKey("LocalizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Novati.API.Models.Entities.ModeloDispositivo", "ModeloDispositivo")
                        .WithMany()
                        .HasForeignKey("ModeloDispositivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Novati.API.Models.Entities.User", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Localizacao");

                    b.Navigation("ModeloDispositivo");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.Ficheiro", b =>
                {
                    b.HasOne("Novati.API.Models.Entities.User", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CriadoPor");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.InstanciaComponente", b =>
                {
                    b.HasOne("Novati.API.Models.Entities.DispositivoFisico", "DispositivoFisico")
                        .WithMany("Instancias")
                        .HasForeignKey("DispositivoFisicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Novati.API.Models.Entities.ModeloComponente", "ModeloComponente")
                        .WithMany()
                        .HasForeignKey("ModeloComponenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DispositivoFisico");

                    b.Navigation("ModeloComponente");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.ItemStock", b =>
                {
                    b.HasOne("Novati.API.Models.Entities.ModeloComponente", "ModeloComponente")
                        .WithMany()
                        .HasForeignKey("ModeloComponenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ModeloComponente");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.Localizacao", b =>
                {
                    b.HasOne("Novati.API.Models.Entities.Localizacao", "Pai")
                        .WithMany("Filhos")
                        .HasForeignKey("PaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pai");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.Mensagem", b =>
                {
                    b.HasOne("Novati.API.Models.Entities.User", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Novati.API.Models.Entities.Solicitacao", "Solicitacao")
                        .WithMany("Mensagens")
                        .HasForeignKey("SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Solicitacao");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.MovimentoStock", b =>
                {
                    b.HasOne("Novati.API.Models.Entities.ItemStock", "ItemStock")
                        .WithMany("Movimentos")
                        .HasForeignKey("ItemStockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemStock");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.Notificacao", b =>
                {
                    b.HasOne("Novati.API.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.OrdemHistorico", b =>
                {
                    b.HasOne("Novati.API.Models.Entities.User", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Novati.API.Models.Entities.OrdemReparo", "Ordem")
                        .WithMany("Historico")
                        .HasForeignKey("OrdemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Ordem");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.OrdemPecaUsada", b =>
                {
                    b.HasOne("Novati.API.Models.Entities.InstanciaComponente", "InstaladoInstancia")
                        .WithMany()
                        .HasForeignKey("InstaladoInstanciaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Novati.API.Models.Entities.ModeloComponente", "ModeloComponente")
                        .WithMany()
                        .HasForeignKey("ModeloComponenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Novati.API.Models.Entities.OrdemReparo", "Ordem")
                        .WithMany("PecasUsadas")
                        .HasForeignKey("OrdemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Novati.API.Models.Entities.UnidadeStock", "UnidadeStock")
                        .WithMany()
                        .HasForeignKey("UnidadeStockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InstaladoInstancia");

                    b.Navigation("ModeloComponente");

                    b.Navigation("Ordem");

                    b.Navigation("UnidadeStock");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.OrdemRejeicao", b =>
                {
                    b.HasOne("Novati.API.Models.Entities.OrdemReparo", "Ordem")
                        .WithMany("Rejeicoes")
                        .HasForeignKey("OrdemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ordem");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.OrdemReparo", b =>
                {
                    b.HasOne("Novati.API.Models.Entities.Solicitacao", "Solicitacao")
                        .WithOne("Ordem")
                        .HasForeignKey("Novati.API.Models.Entities.OrdemReparo", "SolicitacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Novati.API.Models.Entities.User", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitacao");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.RelatorioHistorico", b =>
                {
                    b.HasOne("Novati.API.Models.Entities.User", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Novati.API.Models.Entities.RelatorioTecnico", "Relatorio")
                        .WithMany("Historico")
                        .HasForeignKey("RelatorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Relatorio");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.RelatorioTecnico", b =>
                {
                    b.HasOne("Novati.API.Models.Entities.Ficheiro", "AssinaturaTecnicoFicheiro")
                        .WithMany()
                        .HasForeignKey("AssinaturaTecnicoFicheiroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Novati.API.Models.Entities.User", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Novati.API.Models.Entities.OrdemReparo", "Ordem")
                        .WithOne("Relatorio")
                        .HasForeignKey("Novati.API.Models.Entities.RelatorioTecnico", "OrdemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Novati.API.Models.Entities.PecaRelatorio", "PecasUsadas", b1 =>
                        {
                            b1.Property<Guid>("RelatorioTecnicoId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Codigo")
                                .IsRequired();

                            b1.Property<string>("Nome")
                                .IsRequired();

                            b1.Property<int>("Quantidade");

                            b1.HasKey("RelatorioTecnicoId", "__synthesizedOrdinal");

                            b1.ToTable("RelatoriosTecnicos");

                            b1
                                .ToJson("PecasUsadas")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("RelatorioTecnicoId");
                        });

                    b.Navigation("AssinaturaTecnicoFicheiro");

                    b.Navigation("Autor");

                    b.Navigation("Ordem");

                    b.Navigation("PecasUsadas");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.RequisicaoCompra", b =>
                {
                    b.HasOne("Novati.API.Models.Entities.ItemStock", "ItemStock")
                        .WithMany("Requisicoes")
                        .HasForeignKey("ItemStockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Novati.API.Models.Entities.ModeloComponente", "ModeloComponente")
                        .WithMany()
                        .HasForeignKey("ModeloComponenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Novati.API.Models.Entities.OrdemReparo", "Ordem")
                        .WithMany("Requisicoes")
                        .HasForeignKey("OrdemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Novati.API.Models.Entities.User", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemStock");

                    b.Navigation("ModeloComponente");

                    b.Navigation("Ordem");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.SessaoRemota", b =>
                {
                    b.HasOne("Novati.API.Models.Entities.Solicitacao", "Solicitacao")
                        .WithMany()
                        .HasForeignKey("SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Novati.API.Models.Entities.User", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Novati.API.Models.Entities.User", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitacao");

                    b.Navigation("Solicitante");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.Solicitacao", b =>
                {
                    b.HasOne("Novati.API.Models.Entities.DispositivoFisico", "DispositivoFisico")
                        .WithMany()
                        .HasForeignKey("DispositivoFisicoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Novati.API.Models.Entities.User", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Novati.API.Models.Entities.Anexo", "Anexos", b1 =>
                        {
                            b1.Property<Guid>("SolicitacaoId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("DataUrl");

                            b1.Property<Guid?>("FicheiroId");

                            b1.Property<string>("Nome")
                                .IsRequired();

                            b1.Property<string>("Tipo")
                                .IsRequired();

                            b1.HasKey("SolicitacaoId", "__synthesizedOrdinal");

                            b1.ToTable("Solicitacoes");

                            b1
                                .ToJson("Anexos")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("SolicitacaoId");
                        });

                    b.OwnsOne("Novati.API.Models.Entities.Avaliacao", "Avaliacao", b1 =>
                        {
                            b1.Property<Guid>("SolicitacaoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Comentario")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<DateOnly>("Data")
                                .HasColumnType("date");

                            b1.Property<int>("Estrelas")
                                .HasColumnType("integer");

                            b1.HasKey("SolicitacaoId");

                            b1.ToTable("Solicitacoes");

                            b1.WithOwner()
                                .HasForeignKey("SolicitacaoId");
                        });

                    b.Navigation("Anexos");

                    b.Navigation("Avaliacao");

                    b.Navigation("DispositivoFisico");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.UnidadeStock", b =>
                {
                    b.HasOne("Novati.API.Models.Entities.ItemStock", "ItemStock")
                        .WithMany("Unidades")
                        .HasForeignKey("ItemStockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Novati.API.Models.Entities.OrdemReparo", "ReservadaParaOrdem")
                        .WithMany()
                        .HasForeignKey("ReservadaParaOrdemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ItemStock");

                    b.Navigation("ReservadaParaOrdem");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.User", b =>
                {
                    b.HasOne("Novati.API.Models.Entities.Ficheiro", "AssinaturaFicheiro")
                        .WithMany()
                        .HasForeignKey("AssinaturaFicheiroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssinaturaFicheiro");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.Artigo", b =>
                {
                    b.Navigation("Avaliacoes");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.DispositivoFisico", b =>
                {
                    b.Navigation("Instancias");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.ItemStock", b =>
                {
                    b.Navigation("Movimentos");

                    b.Navigation("Requisicoes");

                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.Localizacao", b =>
                {
                    b.Navigation("Filhos");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.OrdemReparo", b =>
                {
                    b.Navigation("Historico");

                    b.Navigation("PecasUsadas");

                    b.Navigation("Rejeicoes");

                    b.Navigation("Relatorio");

                    b.Navigation("Requisicoes");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.RelatorioTecnico", b =>
                {
                    b.Navigation("Historico");
                });

            modelBuilder.Entity("Novati.API.Models.Entities.Solicitacao", b =>
                {
                    b.Navigation("Mensagens");

                    b.Navigation("Ordem");
                });
#pragma warning restore 612, 618
        }
    }
}
